### ISSUE TITLE
My Cyrillic characters implementation (Duplicate, please delete)

### ISSUE THREAD

**Issue by Phyan** [alif-type/reem-kufi#42] opened 2023-03-24 17:44 UTC
I really wanted to thank you for this wonderful font, which I now have as my main system font on my phone. It looks incredible! 🤩
I was a little upset by the fact that such a cool font has no Cyrillic support and some time ago I decided to add Cyrillic character support to it, and here are some of my workings:
![image](https://user-images.githubusercontent.com/66014175/227600657-90808109-dfd1-4eaf-bbc8-7edfec492ab3.png)
![image](https://user-images.githubusercontent.com/66014175/227600730-aa0cecad-ab7c-4fdc-9bea-d601f685c7ac.png)

If you want, I can give you my workings for further polishing, and possibly releasing them as an official. That would be extremely cool!

**Comment by khaledhosny** [comment] 2023-03-25 00:08
Duplicate of #41.

**Comment by khaledhosny** [comment] 2023-03-25 00:09
Duplicate of #41

**Closed as completed by khaledhosny** 2023-03-25 00:09 UTC
Labels: duplicate
